### ISSUE TITLE
Throw event to resolve a default rate if none could be determined

### ISSUE THREAD

**Issue by upchuk** [upchuk/commerce_bpost#1]
Inside `determinePriceFromWeightSegment()`

**Comment by MrLanceken** [comment]
The module cannot be used until that bug is fixed.

**Comment by upchuk** [comment]
@MrLanceken I made it configurable a few days ago so you can specify a default rate.

**Comment by MrLanceken** [comment]
> @MrLanceken I made it configurable a few days ago so you can specify a default rate.

I have this error in the webdev toolbar:

`An invalid form control with name='plugin[0][target_plugin_configuration][bpost][rate_amounts_wrapper][home_delivery][configuration][home_delivery][international][NL][default][number]' is not focusable.`

**Comment by upchuk** [comment]
Yes, it's probably trying to tell you it's required bu the fieldset is not open. Make sure that for national and each international country you set a default rate.

**Comment by MrLanceken** [comment]
Indeed that is working, but you need to select international shipping rates. If not, you cannot continue. Some do not need international shipping.

**Comment by upchuk** [comment]
There is a checkbox called `Supports international shipping rates`, unchecking that forces you to provide international shipping rates? If so, yeah, it's a bug, I need to fix it.
